{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy import signal\n",
    "from scipy.fft import fft\n",
    "import matplotlib.pyplot as plt\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "class SaccadeAnalyzer:\n",
    "    def __init__(self, df):\n",
    "        \"\"\"\n",
    "        サッカード分析クラスの初期化\n",
    "        \n",
    "        Parameters:\n",
    "        -----------\n",
    "        df : pandas.DataFrame\n",
    "            分析対象のデータフレーム\n",
    "        \"\"\"\n",
    "        self.df = df\n",
    "        self.df['timestamp'] = pd.to_numeric(self.df['timestamp'])  # timestampカラムを数値に変換\n",
    "        self.process_data()\n",
    "    \n",
    "    def process_data(self):\n",
    "        \"\"\"データの前処理とベースとなる計算を行う\"\"\"\n",
    "        # 時間差分の計算\n",
    "        self.dt = np.diff(self.df['timestamp']) / 1000  # msからsに変換\n",
    "        \n",
    "        # 位置の差分を計算\n",
    "        self.dx = np.diff(self.df['RotatedEyeCenterX_DrawPointerX_Diff'])\n",
    "        self.dy = np.diff(self.df['RotatedEyeCenterY_DrawPointerY_Diff'])\n",
    "        \n",
    "        # 速度の計算\n",
    "        self.velocity = np.sqrt(self.dx**2 + self.dy**2) / self.dt\n",
    "        \n",
    "        # 加速度の計算\n",
    "        self.acceleration = np.diff(self.velocity) / self.dt[:-1]\n",
    "        \n",
    "        # 躍度の計算\n",
    "        self.jerk = np.diff(self.acceleration) / self.dt[:-2]\n",
    "    \n",
    "    def calculate_basic_metrics(self):\n",
    "        \"\"\"基本的な統計量を計算\"\"\"\n",
    "        metrics = {\n",
    "            'mean_velocity': np.mean(self.velocity),\n",
    "            'max_velocity': np.max(self.velocity),\n",
    "            'mean_acceleration': np.mean(self.acceleration),\n",
    "            'max_acceleration': np.max(self.acceleration),\n",
    "            'mean_jerk': np.mean(self.jerk),\n",
    "            'max_jerk': np.max(self.jerk)\n",
    "        }\n",
    "        return metrics\n",
    "    \n",
    "    def detect_saccades(self, velocity_threshold=30):\n",
    "        \"\"\"サッカードを検出する\"\"\"\n",
    "        self.saccade_mask = self.velocity > velocity_threshold\n",
    "        saccade_count = np.sum(self.saccade_mask)\n",
    "        \n",
    "        # サッカード中の移動距離を計算\n",
    "        saccade_distance = np.sum(self.velocity[self.saccade_mask] * self.dt[self.saccade_mask])\n",
    "        \n",
    "        # 固視時間を計算\n",
    "        fixation_time = np.sum(self.dt[~self.saccade_mask]) * 1000  # sからmsに変換\n",
    "        \n",
    "        return {\n",
    "            'saccade_count': saccade_count,\n",
    "            'saccade_distance': saccade_distance,\n",
    "            'fixation_time': fixation_time\n",
    "        }\n",
    "    \n",
    "    def calculate_direction_changes(self, angle_threshold=np.pi/4):\n",
    "        \"\"\"方向転換の回数を計算\"\"\"\n",
    "        angles = np.arctan2(self.dy, self.dx)\n",
    "        angle_diff = np.diff(angles)\n",
    "        \n",
    "        # -πとπの境界をまたぐ場合の補正\n",
    "        angle_diff = np.where(angle_diff > np.pi, angle_diff - 2*np.pi,\n",
    "                            np.where(angle_diff < -np.pi, angle_diff + 2*np.pi, angle_diff))\n",
    "        \n",
    "        direction_changes = np.sum(np.abs(angle_diff) > angle_threshold)\n",
    "        direction_change_freq = direction_changes / (self.df['timestamp'].iloc[-1] - self.df['timestamp'].iloc[0]) * 1000\n",
    "        \n",
    "        return {\n",
    "            'direction_changes': direction_changes,\n",
    "            'direction_change_frequency': direction_change_freq\n",
    "        }\n",
    "    \n",
    "    def calculate_fft_metrics(self):\n",
    "        \"\"\"FFT解析を行い、高周波成分の強度を計算\"\"\"\n",
    "        # FFTの計算\n",
    "        fft_result = fft(self.velocity)\n",
    "        freq = np.fft.fftfreq(len(self.velocity), d=np.mean(self.dt))\n",
    "        \n",
    "        # 正の周波数成分のみを使用\n",
    "        pos_freq_mask = freq > 0\n",
    "        power_spectrum = np.abs(fft_result[pos_freq_mask])\n",
    "        freq = freq[pos_freq_mask]\n",
    "        \n",
    "        # 高周波成分（10Hz以上）の強度を計算\n",
    "        high_freq_power = np.sum(power_spectrum[freq > 10])\n",
    "        \n",
    "        return {\n",
    "            'high_freq_power': high_freq_power,\n",
    "            'freq': freq,\n",
    "            'power_spectrum': power_spectrum\n",
    "        }\n",
    "    \n",
    "    def analyze(self):\n",
    "        \"\"\"すべての分析を実行して結果を返す\"\"\"\n",
    "        results = {}\n",
    "        \n",
    "        # 基本的な統計量\n",
    "        results.update(self.calculate_basic_metrics())\n",
    "        \n",
    "        # サッカード関連の指標\n",
    "        results.update(self.detect_saccades())\n",
    "        \n",
    "        # 方向転換の分析\n",
    "        results.update(self.calculate_direction_changes())\n",
    "        \n",
    "        # FFT解析\n",
    "        results.update(self.calculate_fft_metrics())\n",
    "        \n",
    "        return results\n",
    "    \n",
    "    def plot_profiles(self, output_dir, base_name):\n",
    "        \"\"\"速度、加速度、躍度のプロファイルをプロット\"\"\"\n",
    "        fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 10))\n",
    "        \n",
    "        # 速度プロファイル\n",
    "        ax1.plot(self.df['timestamp'][1:], self.velocity)\n",
    "        ax1.set_title('Velocity Profile')\n",
    "        ax1.set_ylabel('Velocity (deg/s)')\n",
    "        \n",
    "        # 加速度プロファイル\n",
    "        ax2.plot(self.df['timestamp'][2:], self.acceleration)\n",
    "        ax2.set_title('Acceleration Profile')\n",
    "        ax2.set_ylabel('Acceleration (deg/s²)')\n",
    "        \n",
    "        # 躍度プロファイル\n",
    "        ax3.plot(self.df['timestamp'][3:], self.jerk)\n",
    "        ax3.set_title('Jerk Profile')\n",
    "        ax3.set_ylabel('Jerk (deg/s³)')\n",
    "        ax3.set_xlabel('Time (ms)')\n",
    "        \n",
    "        plt.tight_layout()\n",
    "        \n",
    "        # プロットを保存\n",
    "        plot_path = os.path.join(output_dir, f'{base_name}_profiles.png')\n",
    "        plt.savefig(plot_path)\n",
    "        plt.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "サッカード分析結果:\n",
      "平均速度: 228.07 deg/s\n",
      "最大速度: 30154.04 deg/s\n",
      "平均加速度: -860.61 deg/s²\n",
      "最大加速度: 1923178.78 deg/s²\n",
      "平均躍度: 85685.40 deg/s³\n",
      "最大躍度: 178687907.09 deg/s³\n",
      "サッカード回数: 746\n",
      "サッカード中の移動距離: 6120.08 deg\n",
      "固視時間: 16802.00 ms\n",
      "方向転換回数: 657\n",
      "方向転換頻度: 23.11 回/s\n",
      "高周波成分の強度: 52439176.72\n"
     ]
    }
   ],
   "source": [
    "def preprocess_data(df):\n",
    "    \"\"\"\n",
    "    データの前処理を行う関数\n",
    "    - 差分列の計算\n",
    "    - カラム名の調整\n",
    "    \"\"\"\n",
    "    # 差分列の計算\n",
    "    df['RotatedEyeCenterX_DrawPointerX_Diff'] = df['RotatedEyeCenterX'] - df['DrawPointerX']\n",
    "    df['RotatedEyeCenterY_DrawPointerY_Diff'] = df['RotatedEyeCenterY'] - df['DrawPointerY']\n",
    "    \n",
    "    # TimeStampカラムの名前を確認し、必要に応じて変更\n",
    "    if 'TimeStamp' in df.columns:\n",
    "        df['timestamp'] = df['TimeStamp']\n",
    "    elif 'timestamp' in df.columns:\n",
    "        df['timestamp'] = df['timestamp']\n",
    "    else:\n",
    "        raise ValueError(\"タイムスタンプのカラムが見つかりません\")\n",
    "    \n",
    "    return df\n",
    "\n",
    "def analyze_eye_movements(input_file, output_dir):\n",
    "    \"\"\"\n",
    "    眼球運動データを分析する関数\n",
    "    \n",
    "    Parameters:\n",
    "    -----------\n",
    "    input_file : str\n",
    "        入力ファイルのパス\n",
    "    output_dir : str\n",
    "        出力ディレクトリのパス\n",
    "    \"\"\"\n",
    "    # データの読み込みと前処理\n",
    "    df = pd.read_csv(input_file)\n",
    "    df = preprocess_data(df)\n",
    "    \n",
    "    # 分析の実行\n",
    "    analyzer = SaccadeAnalyzer(df)\n",
    "    results = analyzer.analyze()\n",
    "    \n",
    "    # 結果を表示\n",
    "    print(\"\\nサッカード分析結果:\")\n",
    "    print(f\"平均速度: {results['mean_velocity']:.2f} deg/s\")\n",
    "    print(f\"最大速度: {results['max_velocity']:.2f} deg/s\")\n",
    "    print(f\"平均加速度: {results['mean_acceleration']:.2f} deg/s²\")\n",
    "    print(f\"最大加速度: {results['max_acceleration']:.2f} deg/s²\")\n",
    "    print(f\"平均躍度: {results['mean_jerk']:.2f} deg/s³\")\n",
    "    print(f\"最大躍度: {results['max_jerk']:.2f} deg/s³\")\n",
    "    print(f\"サッカード回数: {results['saccade_count']}\")\n",
    "    print(f\"サッカード中の移動距離: {results['saccade_distance']:.2f} deg\")\n",
    "    print(f\"固視時間: {results['fixation_time']:.2f} ms\")\n",
    "    print(f\"方向転換回数: {results['direction_changes']}\")\n",
    "    print(f\"方向転換頻度: {results['direction_change_frequency']:.2f} 回/s\")\n",
    "    print(f\"高周波成分の強度: {results['high_freq_power']:.2f}\")\n",
    "    \n",
    "    # 結果をCSVファイルに保存\n",
    "    base_name = os.path.splitext(os.path.basename(input_file))[0]\n",
    "    results_df = pd.DataFrame([results])\n",
    "    results_df.to_csv(os.path.join(output_dir, f'{base_name}_results.csv'), index=False)\n",
    "    \n",
    "    # プロファイルのプロット\n",
    "    analyzer.plot_profiles(output_dir, base_name)\n",
    "    \n",
    "    return results\n",
    "\n",
    "# 実行コード\n",
    "if __name__ == \"__main__\":\n",
    "    # ファイルパスを指定\n",
    "    input_file = r\"G:\\共有ドライブ\\GAP_長寿研\\GAPデータ\\20241009103234_6\\calibration_6_20241009_20241119145059.csv\"\n",
    "    output_dir = r\"G:\\共有ドライブ\\GAP_長寿研\\user\\iwamoto\\視線の動きの俊敏さ\\result\"\n",
    "    \n",
    "    # 分析を実行\n",
    "    results = analyze_eye_movements(input_file, output_dir)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
